EduHomeProject/EduHome.UI/Areas/EduHomeAdmin/Controllers/TestimonialController.cs
using AutoMapper;
using EduHome.Core.Entities;
using EduHome.DataAccess.Contexts;
using EduHome.UI.Areas.EduHomeAdmin.ViewModels.TestimonialViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EduHome.UI.Areas.EduHomeAdmin.Controllers;
[Area("EduHomeAdmin")]

public class TestimonialController : Controller
{
    private readonly AppDbContext _context;
    private readonly IMapper _mapper;
    private readonly IWebHostEnvironment _env;

    public TestimonialController(AppDbContext context, IMapper mapper, IWebHostEnvironment env)
    {
        _context = context;
        _mapper = mapper;
        _env = env;
    }
    [Area("EduHomeAdmin")]
    public async Task<IActionResult> Index()
    {

        List<Testimonial> testimonials = await _context.Testimonials.ToListAsync();
        return View(testimonials);
    }
    [Area("EduHomeAdmin")]
    public async Task<IActionResult> Create()
    {
        ViewBag.Catagories = await _context.Testimonials.ToListAsync();
        return View();
    }
    [Area("EduHomeAdmin")]
    [HttpPost]
    [ActionName("Create")]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> Create(Testimonial testimonial)

    {
        if (!ModelState.IsValid)
        {
            return View(testimonial);
        }
        var testimonialdb = new Testimonial
        {
            ImagePath = testimonial.ImagePath,
            Surname = testimonial.Surname,
            Name = testimonial.Name,
            Position = testimonial.Position,
            Description = testimonial.Description
        };
        await _context.Testimonials.AddAsync(testimonialdb);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));

    }
    [Area("EduHomeAdmin")]
    public async Task<IActionResult> Delete(int id)
    {
        var testimonial = await _context.Testimonials.FindAsync(id);
        if (testimonial == null)
        {
            return NotFound();
        }
        return View(testimonial);
    }
    [Area("EduHomeAdmin")]
    [HttpPost]
    [ActionName("Delete")]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> DeletePost(int id)
    {
        var testimonials = await _context.Testimonials.FindAsync(id);
        if (testimonials == null)
        {
            return NotFound();
        }
        _context.Testimonials.Remove(testimonials);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
    [Area("EduHomeAdmin")]

    [HttpGet]
    public async Task<IActionResult> Update(int id)
    {
        var testimonials = await _context.Testimonials.FindAsync(id);
        if (testimonials == null)
        {
            return NotFound();
        }

        var testimoniaVM = new TestimonialPostVM
        {
            Name = testimonials.Name,
            Surname = testimonials.Surname,
            Position = testimonials.Position,
            Description = testimonials.Description
        };

        return View(testimoniaVM);
    }
    [Area("EduHomeAdmin")]
    [ActionName("Update")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(int id, TestimonialPostVM testimoniaVM)
    {
        if (id != testimoniaVM.Id)
        {
            return BadRequest();
        }

        if (!ModelState.IsValid)
        {
            return View(testimoniaVM);
        }

        Testimonial Testimonials = await _context.Testimonials.FindAsync(id);
        if (Testimonials == null)
        {
            return BadRequest();
        }
        Testimonials.Name = testimoniaVM.Name;
        Testimonials.Surname = testimoniaVM.Surname;
        Testimonials.Position = testimoniaVM.Position;
        Testimonials.ImagePath = testimoniaVM.ImagePath;
        Testimonials.Description = testimoniaVM.Description;
        _context.Entry(Testimonials).State = EntityState.Modified;
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
}

EduHomeProject/EduHome.UI/Areas/EduHomeAdmin/Views/Testimonial/Create.cshtml
@using EduHome.UI.Areas.EduHomeAdmin.ViewModels.TestimonialViewModels;
@model TestimonialPostVM
@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h3 style="color:cornflowerblue">Create Blog</h3>
                <form method="post" enctype="multipart/form-data">
                    @*default orarag get dir*@
                    <div class="mb-3 row">
                        <label asp-for="Name" class="col-md-2 col-form-label"></label>
                        <div class="col-md-10">
                            <input class="form-control" asp-for="Name" />
                            <span class="text-danger" asp-validation-for="Name"></span>
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label asp-for="Surname" class="col-md-2 col-form-label"></label>
                        <div class="col-md-10">
                            <input class="form-control" asp-for="Surname" />
                            <span class="text-danger" asp-validation-for="Surname"></span>
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label asp-for="Position" class="col-md-2 col-form-label"></label>
                        <div class="col-md-10">
                            <input class="form-control" asp-for="Position" />
                            <span class="text-danger" asp-validation-for="Position"></span>
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label asp-for="Description" class="col-md-2 col-form-label"></label>
                        <div class="col-md-10">
                            <input class="form-control" asp-for="Description" />
                            <span class="text-danger" asp-validation-for="Description"></span>
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label asp-for="ImagePath" class="col-md-2 col-form-label"></label>
                        <div class="col-md-10">
                            <input class="form-control" asp-for="ImagePath" />
                            <span class="text-danger" asp-validation-for="ImagePath"></span>
                        </div>
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary ">Submit</button>
                        <a asp-area="EduHomeAdmin" asp-controller="Testimonial" asp-action="Index" class="btn btn-light ">Return</a>
                    </div>
                </form>
            </div>
        </div>
    </div> <!-- end col -->
</div>

EduHomeProject/EduHome.UI/Areas/EduHomeAdmin/Views/Testimonial/Delete.cshtml
@using EduHome.Core.Entities;
@model Testimonial
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/EduHomeAdmin/Views/Shared/_AdminLayout.cshtml";
}
<div class="card">
    <div class="card-body">
        <img src="@Model.ImagePath" style="width:200px" />
        <h4 class="card-title">@Model.</h4>
        <h4 class="card-title-smallTitle">@Model.Name</h4>
        <h4 class="card-title-smallTitle">@Model.Surname</h4>
        <h4 class="card-title-smallTitle">@Model.Position</h4>
        <h4 class="card-title-smallTitle">@Model.Description</h4>
        <p class="card-title-desc">@Model.Description</p>
        <div class="d-flex flex-wrap gap-2">
            <form method="post" asp-route-id="@Model.Id">
                <button type="submit" class="btn btn-danger waves-effect waves-light">Delete</button>
                <a asp-area="EduHomeAdmin" asp-controller="Testimonial" asp-action="Index" class="btn btn-light waves-effect">Back to List</a>
            </form>
        </div>
    </div>
</div>

EduHomeProject/EduHome.UI/Areas/EduHomeAdmin/Views/Testimonial/Index.cshtml
@using EduHome.Core.Entities;
@model IEnumerable<Testimonial>
@{
    ViewData["Title"] = "Index";
    int count = 1;
}

<h1 style="color:cornflowerblue">Testimonial's List</h1>
<a style="margin:20px 0px " asp-action="Create" class="btn btn-primary">Create <i class="far fa-plus-square"></i></a>

<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table mb-0">
                <thead class="table-light">
                    <tr>
                        <th>#</th>
                        <th>Image</th>
                        <th>ImagePath</th>
                        <th>Name</th>
                        <th>Surname</th>
                        <th>Description</th>
                        <th>Decription</th>
                        <th>Position</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                @{
                    var orderedTestimonials = Model.OrderByDescending(testimonial => testimonial.Id);
                }

                @foreach (var testimonial in orderedTestimonials)
                {
                    <tbody>
                        <tr>
                            <th scope="row">@count</th>
                            <td><img width="80" src="@testimonial.ImagePath" alt="section-title"></td>
                            <td>@testimonial.ImagePath</td>
                            <td>@testimonial.Name</td>
                            <td>@testimonial.Surname</td>
                            <td>@testimonial.Description</td>
                            <td>@testimonial.Position</td>
                            <td>
                                <a asp-action="Update" asp-route-id="@testimonial.Id" style="display:flex;align-items:center; gap: 10px; max-width: max-content;" class="btn btn-warning">Update </a>
                            </td>
                            <td>
                                <a asp-action="Delete" asp-route-id="@testimonial.Id" style="display:flex;align-items:center;gap: 10px; max-width: max-content;" class="btn btn-danger">Delete</a>
                            </td>
                        </tr>
                    </tbody>
                    count++;
                }



            </table>
        </div>

    </div>
</div>

EduHomeProject/EduHome.UI/Areas/EduHomeAdmin/Views/Testimonial/Update.cshtml
@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>